validation: sovereign
version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
  mnemonic: dry tribe isolate one magnet undo lawn hollow salmon call loan velvet
- name: frank
  coins:
  - 10000token
  - 100000000stake
  mnemonic: world bamboo diamond grace speak ankle merge hip champion train kit false
faucet:
  name: frank
  coins:
  - 5token
  - 100000stake
client:
  typescript:
    path: ts-client
  hooks:
    path: react/src/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
